type DB={users:any[];profiles:any[];providers:any[];bookings:any[];transactions:any[];messages:any[];reviews:any[]};
const KEY='bookly-local-db-v4';
const seed:DB={users:[],profiles:[],providers:[
{id:'p1',businessName:'Luxe Beauty Studio',ownerName:'Amaka Okafor',category:'Hair & Beauty',city:'Uyo',state:'Akwa Ibom',description:'Premium hair, beauty and styling appointments.',rating:4.9,reviews:128,verified:true,hours:'9:00 AM – 6:00 PM',services:[{id:'luxe-1',name:'Signature Hair Styling',price:18000,duration:90},{id:'luxe-2',name:'Wig Installation',price:25000,duration:120}]},
{id:'p2',businessName:'Ink District Uyo',ownerName:'Divine Arts',category:'Tattoo',city:'Uyo',state:'Akwa Ibom',description:'Custom temporary and permanent tattoo appointments.',rating:4.8,reviews:76,verified:true,hours:'10:00 AM – 7:00 PM',services:[{id:'ink-1',name:'Custom Tattoo Session',price:30000,duration:120},{id:'ink-2',name:'Temporary Tattoo',price:8000,duration:45}]},
{id:'p3',businessName:'PrimeCut Barbers',ownerName:'Samuel Etim',category:'Barber',city:'Calabar',state:'Cross River',description:'Modern cuts, beard grooming and premium barbering.',rating:4.7,reviews:94,verified:true,hours:'8:00 AM – 8:00 PM',services:[{id:'cut-1',name:'Premium Haircut',price:7000,duration:45},{id:'cut-2',name:'Haircut + Beard',price:10000,duration:60}]},
{id:'p4',businessName:'Frame & Focus',ownerName:'Mfon Essien',category:'Photography',city:'Port Harcourt',state:'Rivers',description:'Portrait, event and brand photography.',rating:4.9,reviews:51,verified:true,hours:'8:00 AM – 6:00 PM',services:[{id:'photo-1',name:'Portrait Session',price:45000,duration:90},{id:'photo-2',name:'Brand Shoot',price:85000,duration:180}]},
{id:'p5',businessName:'Glow Nails',ownerName:'Blessing John',category:'Nails',city:'Lagos',state:'Lagos',description:'Clean, stylish manicure and nail art appointments.',rating:4.6,reviews:113,verified:false,hours:'9:00 AM – 6:00 PM',services:[{id:'nail-1',name:'Gel Manicure',price:12000,duration:60},{id:'nail-2',name:'Nail Art',price:18000,duration:90}]},
{id:'p6',businessName:'FitLab Performance',ownerName:'Ibrahim Musa',category:'Fitness',city:'Abuja',state:'FCT',description:'Personal training and fitness coaching.',rating:4.8,reviews:62,verified:true,hours:'6:00 AM – 9:00 PM',services:[{id:'fit-1',name:'Personal Training',price:15000,duration:60},{id:'fit-2',name:'Fitness Assessment',price:10000,duration:45}]}
],bookings:[],transactions:[],messages:[],reviews:[]};
function load():DB{try{const raw=localStorage.getItem(KEY);if(raw){const x=JSON.parse(raw);return {...seed,...x,users:x.users||[],profiles:x.profiles||[],providers:x.providers?.length?x.providers:seed.providers,bookings:x.bookings||[],transactions:x.transactions||[],messages:x.messages||[],reviews:x.reviews||[]}}}catch{}const x=JSON.parse(JSON.stringify(seed));localStorage.setItem(KEY,JSON.stringify(x));return x}
function save(db:DB){localStorage.setItem(KEY,JSON.stringify(db))}
const uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`;
function current(){const raw=localStorage.getItem('bookly-user');return raw?JSON.parse(raw):null}
function profile(db:DB,id:string){return db.profiles.find(x=>x.userId===id)||null}
function result(data:any,status=200){return {data,status}}
async function request(path:string,options:any={}){const db=load(), method=String(options.method||'GET').toUpperCase(), body=options.body?JSON.parse(options.body):{}, url=new URL(path,'http://bookly');const me=current();
if(path==='/auth/signin'&&method==='POST'){let u=db.users.find(x=>x.email===String(body.email||'').toLowerCase());if(!u){u={userId:uid(),name:body.name||'Bookly User',email:String(body.email||'').toLowerCase()};db.users.push(u);save(db)}return result({user:u,token:u.userId})}
if(path==='/api/me'){return result({profile:me?profile(db,me.userId):null})}
if(path==='/api/providers'){let list=db.providers.filter(p=>p.ownerId||!p.ownerId);const q=(url.searchParams.get('q')||'').toLowerCase().trim();if(q)list=list.filter(p=>`${p.businessName} ${p.ownerName||''} ${p.category} ${p.city} ${p.state} ${p.description||''} ${(p.services||[]).map((s:any)=>s.name).join(' ')}`.toLowerCase().includes(q));return result({providers:list})}
if(path.startsWith('/api/providers/')&&path.endsWith('/availability')){const id=path.split('/')[3],p=db.providers.find(x=>x.id===id);if(!p)return result({error:'Provider not found'},404);const date=url.searchParams.get('date')||'';const serviceName=url.searchParams.get('serviceName')||'';const service=(p.services||[]).find((s:any)=>s.id===serviceName||s.name===serviceName);const duration=Number(service?.duration||30);const used=db.bookings.filter(x=>x.providerId===id&&x.date===date&&['pending','approved','rescheduled','reschedule_pending'].includes(x.status));const times=['09:00','09:30','10:00','10:30','11:00','11:30','12:00','12:30','13:00','13:30','14:00','14:30','15:00','15:30','16:00','16:30','17:00'];return result({availableTimes:times.filter(t=>!used.some(x=>x.time===t)),duration})}
if(path==='/api/profile'&&method==='POST'){if(!me)return result({error:'Authentication required'},401);const old=profile(db,me.userId);const next={...(old||{}),...body,id:old?.id||uid(),userId:me.userId,email:body.email||me.email,name:body.name||me.name};if(!['customer','provider'].includes(next.role))return result({error:'Choose Customer or Service Provider'},400);if(old)Object.assign(old,next);else db.profiles.push(next);if(next.role==='provider'){let p=db.providers.find(x=>x.ownerId===me.userId);if(!p){p={id:uid(),ownerId:me.userId,businessName:next.businessName||'Your business',ownerName:next.name||'',category:next.category||'Other Services',city:next.city||'',state:next.state||'',description:next.description||'',rating:5,reviews:0,verified:false,hours:next.hours||'',services:[]};db.providers.push(p)}else Object.assign(p,{businessName:next.businessName||p.businessName,ownerName:next.name||p.ownerName,category:next.category||p.category,city:next.city||p.city,state:next.state||p.state,description:next.description||p.description,hours:next.hours||p.hours})}save(db);return result({profile:next})}
if(path==='/api/bookings'&&method==='GET'){if(!me)return result({error:'Authentication required'},401);const p=profile(db,me.userId);return result({bookings:db.bookings.filter(x=>p?.role==='provider'?x.providerOwnerId===me.userId:(x.customerId===me.userId||x.ownerId===me.userId))})}
if(path==='/api/bookings/create'&&method==='POST'){if(!me)return result({error:'Authentication required'},401);const p=db.providers.find(x=>x.id===body.providerId),s=p?.services?.find((x:any)=>x.id===body.serviceId);if(!p||!s)return result({error:'Provider or service not found'},404);if(db.bookings.some(x=>x.providerId===p.id&&x.date===body.date&&x.time===body.time&&['pending','approved','rescheduled','reschedule_pending'].includes(x.status)))return result({error:'That time is no longer available'},409);const x={id:uid(),providerId:p.id,providerName:p.businessName,providerOwnerId:p.ownerId,customerId:me.userId,ownerId:me.userId,customerName:me.name,serviceId:s.id,serviceName:s.name,price:Number(s.price||0),priceMode:s.priceMode||'fixed',duration:Number(s.duration||60),date:body.date,time:body.time,status:'pending',source:'Bookly',createdAt:new Date().toISOString()};db.bookings.unshift(x);save(db);return result({booking:x},201)}
if(path==='/api/bookings'&&method==='POST'){if(!me)return result({error:'Authentication required'},401);const p=db.providers.find(x=>x.ownerId===me.userId);const x={id:uid(),providerId:p?.id||'manual',providerName:p?.businessName||'',providerOwnerId:me.userId,ownerId:me.userId,customerName:body.customerName||'',serviceName:body.serviceName||'Appointment',price:Number(body.price||0),date:body.date,time:body.time,status:body.status||'approved',source:body.source||'Manual',createdAt:new Date().toISOString()};db.bookings.unshift(x);if(x.price)db.transactions.push({id:uid(),ownerId:me.userId,type:'income',amount:x.price,category:'Booking',description:x.serviceName,date:x.date});save(db);return result({booking:x},201)}
if(path.startsWith('/api/bookings/')&&path.endsWith('/decision')&&method==='POST'){if(!me)return result({error:'Authentication required'},401);const x=db.bookings.find(z=>z.id===path.split('/')[3]);if(!x||x.providerOwnerId!==me.userId)return result({error:'Forbidden'},403);x.status=body.decision;x.declineReason=body.reason||'';if(x.status==='approved')db.transactions.push({id:uid(),ownerId:me.userId,type:'income',amount:x.price,category:'Booking',description:x.serviceName,date:x.date});save(db);return result({booking:x})}
if(path.startsWith('/api/bookings/')&&method==='PUT'){if(!me)return result({error:'Authentication required'},401);const x=db.bookings.find(z=>z.id===path.split('/')[3]);if(!x)return result({error:'Booking not found'},404);if(x.providerOwnerId!==me.userId&&x.customerId!==me.userId)return result({error:'Forbidden'},403);Object.assign(x,body);save(db);return result({booking:x})}
if(path==='/api/services'&&method==='GET'){return result({services:me?db.providers.find(x=>x.ownerId===me.userId)?.services||[]:[]})}
if(path==='/api/services'&&method==='POST'){if(!me)return result({error:'Authentication required'},401);const p=db.providers.find(x=>x.ownerId===me.userId);if(!p)return result({error:'Business profile not found'},404);const s={id:uid(),name:String(body.name||'').trim(),price:Number(body.price||0),priceMode:body.priceMode||'fixed',duration:Number(body.duration||60),description:body.description||''};if(!s.name)return result({error:'Service name is required'},400);p.services=[...(p.services||[]),s];save(db);return result({service:s,services:p.services},201)}
if(path.startsWith('/api/services/')&&method==='PUT'){if(!me)return result({error:'Authentication required'},401);const p=db.providers.find(x=>x.ownerId===me.userId),s=p?.services?.find((x:any)=>x.id===path.split('/')[3]);if(!s)return result({error:'Service not found'},404);Object.assign(s,body);save(db);return result({services:p.services})}
if(path.startsWith('/api/services/')&&method==='DELETE'){if(!me)return result({error:'Authentication required'},401);const p=db.providers.find(x=>x.ownerId===me.userId);if(!p)return result({error:'Business profile not found'},404);p.services=(p.services||[]).filter((x:any)=>x.id!==path.split('/')[3]);save(db);return result({services:p.services})}
if(path==='/api/finance'){if(!me)return result({error:'Authentication required'},401);const t=db.transactions.filter(x=>x.ownerId===me.userId),revenue=t.filter(x=>x.type==='income').reduce((a,x)=>a+Number(x.amount||0),0),expenses=t.filter(x=>x.type==='expense').reduce((a,x)=>a+Number(x.amount||0),0);return result({finance:{revenue,expenses,profit:revenue-expenses,balance:revenue-expenses,transactions:t}})}
if(path==='/api/finance/expenses'&&method==='POST'){if(!me)return result({error:'Authentication required'},401);const t={id:uid(),ownerId:me.userId,type:'expense',amount:Number(body.amount||0),category:body.category||'Other',description:body.description||'',date:body.date||new Date().toISOString().slice(0,10)};db.transactions.push(t);save(db);return result({id:t.id},201)}
if(path==='/api/messages'&&method==='GET'){if(!me)return result({error:'Authentication required'},401);const providerId=url.searchParams.get('providerId');return result({messages:db.messages.filter(x=>(x.senderId===me.userId||x.recipientId===me.userId)&&(!providerId||x.providerId===providerId))})}
if(path==='/api/messages'&&method==='POST'){if(!me)return result({error:'Authentication required'},401);const m={id:uid(),senderId:me.userId,...body,createdAt:new Date().toISOString()};db.messages.push(m);save(db);return result({message:m},201)}
if(path==='/api/provider/messages'){return result({conversations:[]})}
if(path==='/api/reviews'&&method==='GET'){return result({reviews:db.reviews.filter(x=>x.providerId===url.searchParams.get('providerId'))})}
if(path==='/api/reviews'&&method==='POST'){if(!me)return result({error:'Authentication required'},401);const x={id:uid(),...body,customerId:me.userId,createdAt:new Date().toISOString()};db.reviews.push(x);save(db);return result({review:x},201)}
return result({error:'route not found'},404)}
export const api={get:(p:string)=>request(p),post:(p:string,b?:any)=>request(p,{method:'POST',body:JSON.stringify(b||{})}),put:(p:string,b?:any)=>request(p,{method:'PUT',body:JSON.stringify(b||{})}),delete:(p:string)=>request(p,{method:'DELETE'})};
export const auth={async getUser(){return current()},async signIn(){let u=current();if(!u){const name=window.prompt('Your name')||'Bookly User';const email=window.prompt('Email')||`user${Date.now()}@bookly.local`;const r=await request('/auth/signin',{method:'POST',body:JSON.stringify({name,email})});u=r.data.user;localStorage.setItem('bookly-user',JSON.stringify(u))}return {user:u}},async signOut(){localStorage.removeItem('bookly-user')}};
export const ws={connect(){return {onMessage(){},onError(){},ready:Promise.resolve({connectionId:''}),disconnect(){}}}};
